version: "3.0"
services:
  db-authentication:
    image: mysql:8.0.28
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=bdsm_authentication
    ports:
      - 6061:3306
    command: mysqld --lower_case_table_names=1 --sql_mode='' --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --bind-address=0.0.0.0
  authentication:
    depends_on:
      - db-authentication
    image: haitranquangofficial/buda:authentication-app
    restart: always
    ports:
      - 6060:6060
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-authentication:3306/bdsm_authentication
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    stdin_open: true
    tty: true
    security:
    oauth2:
      client:
        registration:
         facebook:
          clientId: 567324301919108
          clientSecret: 09b0c207fc43f8fcb24c12d2a5d4653f
          scope:
           - email
           - public_profile   
volumes:
  db-authentication: